package com.hesicare.com.wsbs.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-15T15:10:21.763+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://service.ws.check.basic.health.yxhaibo.com/", name = "SyncInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface SyncInfoService {

    @WebMethod
    @RequestWrapper(localName = "setBGResult", targetNamespace = "http://service.ws.check.basic.health.yxhaibo.com/", className = "com.hesicare.com.wsbs.client.service.SetBGResult")
    @ResponseWrapper(localName = "setBGResultResponse", targetNamespace = "http://service.ws.check.basic.health.yxhaibo.com/", className = "com.hesicare.com.wsbs.client.service.SetBGResultResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Object setBGResult(

        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "serialNumber", targetNamespace = "")
        String serialNumber,
        @WebParam(name = "bloodSugar", targetNamespace = "")
        String bloodSugar
    );

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://service.ws.check.basic.health.yxhaibo.com/", className = "com.hesicare.com.wsbs.client.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.ws.check.basic.health.yxhaibo.com/", className = "com.hesicare.com.wsbs.client.service.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Object login(

        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "secretKey", targetNamespace = "")
        String secretKey
    );

    @WebMethod
    @RequestWrapper(localName = "getPatientInfo", targetNamespace = "http://service.ws.check.basic.health.yxhaibo.com/", className = "com.hesicare.com.wsbs.client.service.GetPatientInfo")
    @ResponseWrapper(localName = "getPatientInfoResponse", targetNamespace = "http://service.ws.check.basic.health.yxhaibo.com/", className = "com.hesicare.com.wsbs.client.service.GetPatientInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Object getPatientInfo(

        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "serialNumber", targetNamespace = "")
        String serialNumber
    );
}
