package com.hesicare.com.wsbs.client.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-15T15:10:21.797+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "SyncInfoServiceImplService",
                  wsdlLocation = "http://120.24.224.4:8384/services/SyncInfoService?wsdl",
                  targetNamespace = "http://service.ws.check.basic.health.yxhaibo.com/")
public class SyncInfoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.check.basic.health.yxhaibo.com/", "SyncInfoServiceImplService");
    public final static QName SyncInfoServiceImplPort = new QName("http://service.ws.check.basic.health.yxhaibo.com/", "SyncInfoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://120.24.224.4:8384/services/SyncInfoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SyncInfoServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://120.24.224.4:8384/services/SyncInfoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SyncInfoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SyncInfoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncInfoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SyncInfoServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SyncInfoServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SyncInfoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SyncInfoService
     */
    @WebEndpoint(name = "SyncInfoServiceImplPort")
    public SyncInfoService getSyncInfoServiceImplPort() {
        return super.getPort(SyncInfoServiceImplPort, SyncInfoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SyncInfoService
     */
    @WebEndpoint(name = "SyncInfoServiceImplPort")
    public SyncInfoService getSyncInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SyncInfoServiceImplPort, SyncInfoService.class, features);
    }

}
